main: me.LynSnow.ParkourNyan.Main.ParkourNyan
name: ParkourNyan
version: 1.2.1
author: LynSnow
api-version: 1.15
softdepend: [Vault, PlaceholderAPI, HolographicDisplays]

commands:
  parkournyan:
    aliases: pn
